In [26]:
import pandas as pd
df = pd.read_csv('2022_world_cup_groups.csv')
df1 = pd.read_csv('2022_world_cup_matches.csv')
df2 = pd.read_csv('data_dictionary.csv')
df3 = pd.read_csv('international_matches.csv')
df4 = pd.read_csv('world_cup_matches.csv')
df5 = pd.read_csv('world_cups.csv')

In [47]:
df5

,Year,Host Country,Winner,Runners-Up,Third,Fourth,Goals Scored,Qualified Teams,Matches Played
0,1930,Uruguay,Uruguay,Argentina,USA,Yugoslavia,70.0,13,18
1,1934,Italy,Italy,Czechoslovakia,Germany,Austria,70.0,16,17
2,1938,France,Italy,Hungary,Brazil,Sweden,84.0,15,18
3,1950,Brazil,Uruguay,Brazil,Sweden,Spain,88.0,13,22
4,1954,Switzerland,Germany FR,Hungary,Austria,Uruguay,140.0,16,26
5,1958,Sweden,Brazil,Sweden,France,Germany FR,126.0,16,35
6,1962,Chile,Brazil,Czechoslovakia,Chile,Yugoslavia,89.0,16,32
7,1966,England,England,Germany FR,Portugal,Soviet Union,89.0,16,32
8,1970,Mexico,Brazil,Italy,Germany FR,Uruguay,95.0,16,32
9,1974,Germany,Germany FR,Netherlands,Poland,Brazil,97.0,16,38
10,1978,Argentina,Argentina,Netherlands,Brazil,Italy,102.0,16,38
11,1982,Spain,Italy,Germany FR,Poland,France,146.0,24,52
12,1986,Mexico,Argentina,Germany FR,France,Belgium,132.0,24,52
13,1990,Italy,Germany FR,Argentina,Italy,England,115.0,24,52
14,1994,USA,Brazil,Italy,Sweden,Bulgaria,141.0,24,52
15,1998,France,France,Brazil,Croatia,Netherlands,171.0,32,64
16,2002,Korea/Japan,Brazil,Germany,Turkey,Korea Republic,161.0,32,64
17,2006,Germany,Italy,France,Germany,Portugal,147.0,32,64
18,2010,South Africa,Spain,Netherlands,Germany,Uruguay,145.0,32,64
19,2014,Brazil,Germany,Argentina,Netherlands,Brazil,171.0,32,64
20,2018,Russia,France,Croatia,Belgium,England,169.0,32,64
21,2022,Qatar,NaN,NaN,NaN,NaN,NaN,32,64

In [51]:
winners = df5.Winner

0        Uruguay
1          Italy
2          Italy
3        Uruguay
4     Germany FR
5         Brazil
6         Brazil
7        England
8         Brazil
9     Germany FR
10     Argentina
11         Italy
12     Argentina
13    Germany FR
14        Brazil
15        France
16        Brazil
17         Italy
18         Spain
19       Germany
20        France
21           NaN
Name: Winner, dtype: object